### ISSUE TITLE
Live reloading translations is not working

### ISSUE THREAD

**Issue by BeauvR** [intlify/bundle-tools#153]
### Reporting a bug?

We just upgraded to vite version 3 and vite-plugin-vue-i18n to version 5, and reloading translations is not working. We detected this problem by starting a new project, but also found this problem with an old project.

I've tested it with vite version 2 and vite-plugin-vue-i18n version 3 before upgrading and everything worked as expected, after upgrading both packages the translations won't reload. In the vite console, there is also no message the translations are modified. After re-running the vite dev server, the new translations are working.

### Expected behavior

I expect in the console to see the message:
12:34:14 PM [vite] page reload lang/nl.json

And also that the page is reloading.

### Reproduction

- Upgrade an already working project or create a new project with vite version 3 & vite-plugin-vue-i18n version 5
- Run the vite dev server
- Modify any translation

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 294.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.2/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox Developer Edition: 103.0
    Safari: 15.5
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^5.0.0 => 5.0.1 
    vite: ^3.0.0 => 3.0.3 
    vue: ^3.2.37 => 3.2.37 
    vue-i18n: ^9.1.10 => 9.1.10
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by HabardiT** [comment]
I have the same behavior as well. after upgrading from vite-plugin-vue-i18n 3 to 5.

custom i18n blocks in SFCs reloads as expected. however translations imported in **vite.config.ts** don't.

`export default defineConfig({
    plugins: [
        vue(),
        vueI18n({
            include: path.resolve(__dirname, "./src/locales/**.yaml"),
        }),
    ]
});`

**Comment by HabardiT** [comment]
importing messages from json actual path instead of "@intlify/vite-plugin-vue-i18n/messages", then appending it to
**createI18n** is a work-around.

unfortunately I'm using yaml instead of json :(

**Comment by kazupon** [comment]
Could you give minimue reproduction repo to us please?

**Comment by marekvospel** [comment]
@kazupon I've also experienced this issue.  
Here is a minimum reproduction repository: https://github.com/marekvospel/vue-i18n-live-reload

**Comment by kazupon** [comment]
@marekvospel 
Thank you for your reproduction repo!
I could reproduce this issue!
I'll try to fixing!

**Comment by kazupon** [comment]
Hmm 🤔 , This issue might be in vite.

I have found out the cause, but I could not figure it out.
I have confirmed the implementation of the HMR feature, but have not specifically changed it since v3.
The supported version is v2.2.0.
https://github.com/intlify/bundle-tools/commit/c6e0e2c0d45d37c77cc2cc58feafdc81eba0cd51

In vite v3, experimental HMR feature has been released.
https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#300-2022-07-13

And also there are several HMR fixes in the later v2 version.
Since that time, vite may have a regression.

We need to find out which version we have the problem from, whether vite 3 or some version of vite 2.

**Comment by tlebeitsuk** [comment]
Resolved in Vite v3.0.5.

**Comment by c-harding** [comment]
Unfortunately I can still reproduce the issue both in my own repo and in @marekvospel’s minimal one using Vite v3.0.5

**Comment by ghostiam** [comment]
I think the problem is the wrong ID.
https://github.com/intlify/bundle-tools/blob/main/packages/vite-plugin-vue-i18n/src/index.ts#L22

I have created a simple plugin and this is what I get with different IDs:

```ts
function I18nHotReload(): PluginOption {
  return {
    name: "i18n-hot-reload",
    handleHotUpdate({ file, server }) {
      console.log(file)

      const module = server.moduleGraph.getModuleById("@intlify/vite-plugin-vue-i18n/messages")
      console.log(module) // <- undefined

      const module2 = server.moduleGraph.getModuleById("\x00@intlify/vite-plugin-vue-i18n/messages")
      console.log(module2) // <- ModuleNode
    },
  }
}
```

**Comment by marekvospel** [comment]
> And got a working reload, but the whole page.
currently hmr only works by reloading the page.
https://github.com/intlify/bundle-tools/issues/41

**Comment by kazupon** [comment]
I've just released v6.0.1 
https://github.com/intlify/bundle-tools/releases/tag/vite-plugin-vue-i18n%406.0.1

please check it!

**Comment by BeauvR** [comment]
Thanks it's working now!

**Comment by hooray** [comment]
Same problem in unplugin-vue-i18n

**Comment by marekvospel** [comment]
@hooray 
there's no hot update handler in `unplugin-vue-i18n` (https://github.com/intlify/bundle-tools/blob/main/packages/unplugin-vue-i18n/src/index.ts)

I think separate issue tagged as `enhancement` should be added

\* vite-plugin-vue-i18n's hot update implementation
https://github.com/intlify/bundle-tools/blob/main/packages/vite-plugin-vue-i18n/src/index.ts#L277

**Comment by kazupon** [comment]
I've just supported HRM for vite at v0.7.0
https://github.com/intlify/bundle-tools/releases/tag/unplugin-vue-i18n%400.7.0

Please check it! 😉
